### ISSUE TITLE
Install failure on minor dialogue restorations

### ISSUE THREAD

**Issue by agb1** [AstroBryGuy/bg1ub#2]
Solution:  https://github.com/omni-axa/BiG-World-Fixpack/commit/4ccd747d984fc892c17d8b9855da11a3cb0cd4b3

Problem:  http://www.shsforums.net/topic/56670-big-world-setup-an-attempt-to-update-the-program/page-95#entry583005

**Comment by AstroBryGuy** [comment]
Already fixed in commit 7e25fb67edc1e67a908e438be1a350a712571d66
