### ISSUE TITLE
Strange strings in audio restorations

### ISSUE THREAD

**Issue by burner1024** [AstroBryGuy/bg1ub#5]
I'm getting supposedly tags inserted into literal strings. I'm using an older version (beta 150720 BWP), but as far as I can see, the code is still the same.

![screenshot](https://cloud.githubusercontent.com/assets/1279852/13022945/f999e2d2-d216-11e5-9675-fd48c95275c9.png)

**Comment by AstroBryGuy** [comment]
Not a bug. This is consistent with BG1's strings.

Stringref 3668 in DIALOG.TLK from BG1-TotSC:

`[GARRICK 13] 'Tis a beautiful day in the neighborhood. `

**Comment by burner1024** [comment]
It's not bg1, it's bgt

**Comment by AstroBryGuy** [comment]
The Audio Restorations component restores that line for both Tutu/BGT and BG1-TotSC. BG1UB uses the BG1-style syntax with the bracketed audio information, not the BG2-style.

**Comment by burner1024** [comment]
Thank you for clarification.
